<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>BackToTheDawn.PhoneAPI</AssemblyName>
    <RootNamespace>BackToTheDawn.PhoneAPI</RootNamespace>
    <Version>0.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BackToTheDawn.ModAPI\BackToTheDawn.ModAPI.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
