<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>BackToTheDawn.ModAPI.ResourceTests</AssemblyName>
    <RootNamespace>BackToTheDawn.ModAPI.ResourceTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BackToTheDawn.ModAPI\BackToTheDawn.ModAPI.csproj" />
  </ItemGroup>
</Project>
